"""
=========================================================
Python Logging and Exception Handling
=========================================================

Author      : Dhruvi Raval
Repository  : Python for AI Engineering
Module      : 08 - Exception Handling
File        : 07_logging_exceptions.py

Description
-----------
Logging is used to record important events, warnings,
errors, and debugging information generated by a program.

In production applications, logging is much more useful
than using print() for tracking errors and application
behavior.

Topics Covered
--------------
✔ What is Logging?
✔ logging Module
✔ Log Levels
✔ DEBUG
✔ INFO
✔ WARNING
✔ ERROR
✔ CRITICAL
✔ Logging Exceptions
✔ Exception Traceback
✔ Logging to File
✔ AI/ML Application Example
✔ Best Practices
"""

import logging


print("=" * 60)
print("LOGGING AND EXCEPTION HANDLING")
print("=" * 60)


# =====================================================
# Example 1 - Basic Logging
# =====================================================

print("\nExample 1 - Basic Logging")

logging.basicConfig(
    level=logging.INFO
)

logging.info("Application started.")

# =====================================================
# Example 2 - Log Levels
# =====================================================

print("\nExample 2 - Log Levels")

logging.debug("Debug message.")
logging.info("Information message.")
logging.warning("Warning message.")
logging.error("Error message.")
logging.critical("Critical message.")

print("""
Python logging levels:

DEBUG
INFO
WARNING
ERROR
CRITICAL
""")

# =====================================================
# Example 3 - Logging Information
# =====================================================

print("\nExample 3 - INFO")

logging.info(
    "User successfully logged in."
)

logging.info(
    "Dataset loading started."
)

# =====================================================
# Example 4 - Warning
# =====================================================

print("\nExample 4 - WARNING")

accuracy = 72

if accuracy < 80:

    logging.warning(
        "Model accuracy is below 80%%."
    )

# =====================================================
# Example 5 - Logging an Error
# =====================================================

print("\nExample 5 - ERROR")

try:

    result = 10 / 0

except ZeroDivisionError:

    logging.error(
        "Division by zero occurred."
    )

# =====================================================
# Example 6 - Logging Exception Details
# =====================================================

print("\nExample 6 - Exception Details")

try:

    number = int("Python")

except ValueError as error:

    logging.error(
        "Invalid number: %s",
        error
    )

# =====================================================
# Example 7 - logging.exception()
# =====================================================

print("\nExample 7 - logging.exception()")


def divide(a, b):

    try:

        return a / b

    except ZeroDivisionError:

        logging.exception(
            "Division failed."
        )

        return None


divide(10, 0)

# =====================================================
# Example 8 - File Logging
# =====================================================

print("\nExample 8 - File Logging")

file_logger = logging.getLogger("file_logger")

file_logger.setLevel(logging.INFO)

file_handler = logging.FileHandler(
    "application.log"
)

file_formatter = logging.Formatter(
    "%(asctime)s - %(levelname)s - %(message)s"
)

file_handler.setFormatter(
    file_formatter
)

file_logger.addHandler(
    file_handler
)

file_logger.info(
    "Application log file created."
)

file_logger.warning(
    "This is a warning."
)

# =====================================================
# Example 9 - Logging User Operations
# =====================================================

print("\nExample 9 - User Operations")


def login(username):

    if not username:

        logging.warning(
            "Login attempt with empty username."
        )

        return False

    logging.info(
        "User '%s' logged in.",
        username
    )

    return True


login("Dhruvi")

login("")

# =====================================================
# Example 10 - Logging Exceptions in Functions
# =====================================================

print("\nExample 10 - Function Exception")


def convert_to_integer(value):

    try:

        return int(value)

    except ValueError:

        logging.exception(
            "Failed to convert value: %s",
            value
        )

        return None


convert_to_integer("100")

convert_to_integer("Python")

# =====================================================
# Example 11 - AI Engineering Example
# =====================================================

print("\nExample 11 - AI Model Logging")


ai_logger = logging.getLogger(
    "ai_model"
)


def load_model(model_path):

    ai_logger.info(
        "Loading model from %s",
        model_path
    )

    if not model_path:

        ai_logger.error(
            "Model path is empty."
        )

        return False

    ai_logger.info(
        "Model loaded successfully."
    )

    return True


load_model(
    "models/classifier.pkl"
)

load_model("")

# =====================================================
# Example 12 - Dataset Logging
# =====================================================

print("\nExample 12 - Dataset Logging")


def load_dataset(dataset):

    logging.info(
        "Dataset loading started."
    )

    try:

        if dataset is None:

            raise ValueError(
                "Dataset cannot be None."
            )

        if len(dataset) == 0:

            raise ValueError(
                "Dataset is empty."
            )

        logging.info(
            "Dataset loaded successfully. Rows: %d",
            len(dataset)
        )

    except ValueError:

        logging.exception(
            "Dataset loading failed."
        )


load_dataset(
    [10, 20, 30, 40]
)

load_dataset([])

# =====================================================
# Example 13 - Model Prediction Logging
# =====================================================

print("\nExample 13 - Prediction Logging")


def predict(value):

    logging.info(
        "Prediction request received."
    )

    try:

        number = float(value)

        prediction = number * 2

        logging.info(
            "Prediction completed successfully."
        )

        return prediction

    except ValueError:

        logging.exception(
            "Prediction failed because input "
            "was invalid."
        )

        return None


print(
    "Prediction:",
    predict("10.5")
)

print(
    "Prediction:",
    predict("AI")
)

# =====================================================
# Example 14 - Critical Error
# =====================================================

print("\nExample 14 - CRITICAL")


def database_connection(connected):

    if not connected:

        logging.critical(
            "Database connection is unavailable."
        )

        return False

    logging.info(
        "Database connection established."
    )

    return True


database_connection(False)

# =====================================================
# Log Format
# =====================================================

print("\nLog Format")

print("""
A common logging format is:

%(asctime)s
%(levelname)s
%(message)s

Example:

2026-08-22 10:30:00
INFO
Model training started.
""")

# =====================================================
# Logging vs print()
# =====================================================

print("\nLogging vs print()")

print("""
print()
-------
✔ Quick debugging
✔ Simple scripts

logging
-------
✔ Production applications
✔ Different severity levels
✔ Log files
✔ Timestamps
✔ Error tracking
✔ Debugging production systems
""")

# =====================================================
# Common Mistakes
# =====================================================

print("\nCommon Mistakes")

print("""
❌ Using print() everywhere in production.

❌ Logging sensitive information.

❌ Logging passwords or API keys.

❌ Using only ERROR logs.

❌ Creating too many logging handlers.

❌ Ignoring exception tracebacks.

❌ Using unclear log messages.
""")

# =====================================================
# Best Practices
# =====================================================

print("\nBest Practices")

print("""
✔ Use logging instead of print()
  for production applications.

✔ Use appropriate log levels.

✔ Include useful context.

✔ Use logging.exception() inside
  exception handlers when traceback
  information is needed.

✔ Never log passwords, tokens,
  API keys, or sensitive data.

✔ Store production logs safely.

✔ Use structured logging in large systems.

✔ Rotate large log files when necessary.
""")

# =====================================================
# Interview Questions
# =====================================================

print("\nInterview Questions")

print("""
Q. What is logging?

A. Logging is the process of recording
application events, warnings, errors,
and debugging information.

Q. Which module is used for logging?

A. Python's built-in logging module.

Q. What are the standard logging levels?

A.
DEBUG
INFO
WARNING
ERROR
CRITICAL

Q. What is logging.exception()?

A. It logs an error message along with
exception traceback information.

Q. Why is logging better than print()
in production?

A. Logging provides severity levels,
timestamps, configurable handlers,
and persistent log storage.

Q. Should passwords be logged?

A. No. Sensitive information should
never be written to logs.
""")

# =====================================================
# Summary
# =====================================================

print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)

print("""
✔ Logging records application events.

✔ Python provides the built-in logging module.

✔ Log levels describe the importance
  of an event.

✔ logging.exception() is useful when
  handling exceptions.

✔ Logs are essential for production
  debugging and monitoring.

✔ AI/ML applications can log model
  loading, training, prediction,
  dataset processing, and failures.
""")
